config/routes.rb
Rails.application.routes.draw do
  root 'tools#index'
  get "/tools", to: "tools#index", as: "tools"
  get "/tools/new", to: "tools#new", as: "new_tool"
  get "/tools/:id", to: "tools#show", as: "tool"
  post "/tools", to: "tools#create"
  get "/tools/:id/edit", to: "tools#edit", as: "edit_tool"
  patch "/tools/:id", to: "tools#update"
  put "/tools/:id", to: "tools#update"
  delete "/tools/:id", to: "tools#destroy"
end

app/models/concerns/tool.rb
class Tool < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = Tool.all
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.create(:name => params[:tool]["name"], :price => params[:tool]["price"], :quantity => params[:tool]["quantity"])
    redirect_to tool_path(@tool)
  end

  def edit
    @tool = Tool.find(params[:id])
  end

   def update
    @tool = Tool.find(params[:id])
    @tool.update_attributes(:name => params[:tool]["name"], :price => params[:tool]["price"], :quantity => params[:tool]["quantity"])
    redirect_to tool_path
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.delete
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolsCrud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tools/edit.html.erb
<h1>Tool Edit</h1>

<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.submit %>
<% end %>

app/views/tools/index.html.erb
<h1>Tools Index</h1>

<% @tools.each do |tool| %>
  <div>
    <%= link_to tool.name, tool_path(tool) %>
    | Quantity: <%= tool.quantity %>
    | Price: <%= tool.price %>
  </div>
<% end %>

<%= link_to "Tool Index", tools_path %>
<%= link_to "Tool New", new_tool_path %>

app/views/tools/new.html.erb
<h1>Tool New</h1>

<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.submit %>
<% end %>

app/views/tools/show.html.erb
<h1>Tool Show</h1>

<h3><%= @tool.name %></h3>
<p>Quantity: <%= @tool.quantity %></p>
<p>Price: <%= @tool.name %></p>

<%= link_to "Edit", edit_tool_path(@tool) %>
<%= link_to "Delete", tool_path(@tool), method: 'delete' %>